pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Pine Labs billing SDK — local Maven bundle (AppToApp transport)
        maven {
            url = uri("app/libs/pine-billing-sdk-android-maven")
        }
    }
}
rootProject.name = "BreadChapterPOS"
include(":app")
